<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-N7K85DJ" name="Casuality_Dev_TC.Menu_Press_Room" tests="2" failures="0" timestamp="10 Feb 2022 14:49:42 GMT" time="93.843" errors="2">
  <testcase name="HomePage" time="51.537" classname="Casuality_Dev_TC.Menu_Press_Room">
    <error type="java.lang.AssertionError" message="expected [QBE Lawsuits against Former Individual Employees and against Applied Underwriters, their New Employer, Termed “Meritless” by Applied’s General Counsel] but found [placeholder title]">
      <![CDATA[java.lang.AssertionError: expected [QBE Lawsuits against Former Individual Employees and against Applied Underwriters, their New Employer, Termed “Meritless” by Applied’s General Counsel] but found [placeholder title]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at Casuality_pages.Menu_PressRoom.text_1(Menu_PressRoom.java:94)
	at Casuality_Dev_TC.Menu_Press_Room.HomePage(Menu_Press_Room.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- HomePage -->
  <testcase name="HomePage" time="42.306" classname="Casuality_Dev_TC.Menu_Press_Room">
    <error type="java.lang.AssertionError" message="expected [QBE Lawsuits against Former Individual Employees and against Applied Underwriters, their New Employer, Termed “Meritless” by Applied’s General Counsel] but found [placeholder title]">
      <![CDATA[java.lang.AssertionError: expected [QBE Lawsuits against Former Individual Employees and against Applied Underwriters, their New Employer, Termed “Meritless” by Applied’s General Counsel] but found [placeholder title]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at Casuality_pages.Menu_PressRoom.text_1(Menu_PressRoom.java:94)
	at Casuality_Dev_TC.Menu_Press_Room.HomePage(Menu_Press_Room.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- HomePage -->
</testsuite> <!-- Casuality_Dev_TC.Menu_Press_Room -->
