<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
    <line>
      <![CDATA[=====Chrome Browser Session Started=====]]>
    </line>
    <line>
      <![CDATA[=====Application Started=====]]>
    </line>
  </reporter-output>
  <suite name="Default suite" duration-ms="35931" started-at="2022-03-09T09:56:02Z" finished-at="2022-03-09T09:56:38Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="35931" started-at="2022-03-09T09:56:02Z" finished-at="2022-03-09T09:56:38Z">
      <class name="Aerospace_TestCases_Development.Menu_Aviation">
        <test-method status="PASS" signature="setupApplication()[pri:0, instance:Aerospace_TestCases_Development.Menu_Aviation@2aafb23c]" name="setupApplication" is-config="true" duration-ms="7260" started-at="2022-03-09T15:26:02Z" finished-at="2022-03-09T15:26:09Z">
          <reporter-output>
            <line>
              <![CDATA[=====Chrome Browser Session Started=====]]>
            </line>
            <line>
              <![CDATA[=====Application Started=====]]>
            </line>
          </reporter-output>
        </test-method> <!-- setupApplication -->
        <test-method status="FAIL" signature="Home_Menu_Aeviation()[pri:0, instance:Aerospace_TestCases_Development.Menu_Aviation@2aafb23c]" name="Home_Menu_Aeviation" duration-ms="28646" started-at="2022-03-09T15:26:09Z" finished-at="2022-03-09T15:26:38Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:286)
	at org.testng.Assert.assertEquals(Assert.java:296)
	at Aerospace_Pages.Aviation.Section4(Aviation.java:102)
	at Aerospace_TestCases_Development.Menu_Aviation.Home_Menu_Aeviation(Menu_Aviation.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Home_Menu_Aeviation -->
      </class> <!-- Aerospace_TestCases_Development.Menu_Aviation -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
